# Generated by Django 4.1.7 on 2023-03-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('professor_text', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=15)),
                ('time_text', models.CharField(max_length=15)),
                ('has_meetings', models.BooleanField()),
                ('has_discussion', models.BooleanField()),
                ('num_sections', models.IntegerField()),
                ('num_office_hours', models.IntegerField()),
                ('num_tas', models.IntegerField()),
            ],
        ),
    ]
