# Generated by Django 4.1.7 on 2023-03-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
