# Generated by Django 4.1.7 on 2023-03-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0003_alter_course_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
